package app.rekord.domain.shared.error;

/** The domain's hand-kept copy of the contract's ErrorCode enum, so the domain never depends on generated code; ErrorCodeContractTest binds it to the pinned contract. */
public enum ErrorCode {
    NO_LIBRARY, NO_LIBRARY_SELECTED, EMPTY_NAME, DUPLICATE_NAME, NO_SOURCE, EMPTY_FILE, FILE_TOO_LARGE, BAD_XML,
    BAD_PLAYLIST, NOTHING_RESOLVED, NO_PLAYLIST, FOLDER_NOT_FOUND, SCAN_IN_PROGRESS, BAD_URL,
    SPOTIFY_FETCH_FAILED, SPOTIFY_PARSE_FAILED, NO_TRACKS, UNKNOWN_TRACK, NO_PREFERENCE, SEARCH_UNAVAILABLE,
    RATE_LIMITED, NOTHING_SKIPPED, LIST_FULL, UID_CONFLICT, UNKNOWN_ENTRY, EMPTY_TITLE,
    BAD_LINK, LINK_REVOKED, LINK_EXPIRED, CODE_LOCKED, NOT_SIGNED_IN, FORBIDDEN, BAD_CREDENTIALS,
    ACCOUNT_DISABLED, DUPLICATE_USERNAME, NO_USER, LAST_ADMIN, INVITE_INVALID, INVITE_EXPIRED, NO_WEDDING,
    NO_VENDOR, NO_TASK, VALIDATION_FAILED
}
